### ISSUE TITLE
Support other cache storage backends

### ISSUE THREAD

**Issue by roscopecoltran** [krakendio/krakend-httpcache#1]
Hi guys,

Hope you are all well again !

How would you integrate an api proxy like [sourcegraph's apiproxy](https://github.com/sourcegraph/apiproxy ) to manage MaxAge revalidation values per krakend routes in the config file ? 

And, I extend my question with other cache storage backends as you can use several with gregjones' package. (https://github.com/gregjones/httpcache#cache-backends). So how can I extend krakend-httpcache plugin to manage specific configs for local or cloud backends like redis, badger or  azurestorage.

**httpcache storage configs examples:**
- **Local/Badger** https://github.com/sniperkit/cache/blob/sniperkit/backend/local/badger/handler.go#L49-L103
- **Local/BoltDB** https://github.com/sniperkit/cache/blob/sniperkit/backend/local/boltdb/handler.go#L47-L51
- **Cloud/GCS**: https://github.com/sniperkit/cache/blob/sniperkit/backend/cloud/gcs/config.go#L11-L23
- **Cloud/AzureStorage**: https://github.com/sniperkit/cache/blob/sniperkit/backend/cloud/azurestorage/config.go#L11-L16

The idea is to gain some flexibity on caching content from rate limited api providers, like github.com,..., and to gain manage it from the config file. Use case: integration of krakend with [flogo](https://github.com/TIBCOSoftware/flogo) and the flogo webui. 

Cheers,
Rosco

**Comment by kpacha** [comment]
Hi,

in order to extend this small adapter, I think you just need to change the way the `memTransport` is instantiated [here](https://github.com/devopsfaith/krakend-httpcache/blob/master/http.go#L17).

you can also extend the config used by it so users could select the backend for the cache storage.

cheers
