### ISSUE TITLE
Support overwriting cache lifetime

### ISSUE THREAD

**Issue by L3tum** [krakendio/krakend-httpcache#2]
Hey, I'm wondering if it would be possible to support overwriting the cache lifetime in the config.

My usecase specifically is a very short cache (~30s or so) to keep the load on the backends low. However, I do not want to set this as the Cache-Control header on the backend (particularly because I don't have control over all backends). 

I don't have any knowledge of Go at all so I can't really do a PR right now.

**Comment by kpacha** [comment]
for a more complex and customized cache behaviors, you should use an external service -such as varnish- sitting between your gateway and the backends you want to protect from the load
