### ISSUE TITLE
caching without Cache-Control: public, max-age from backend

### ISSUE THREAD

**Issue by nabinkumar** [krakendio/krakend-httpcache#3]
i am trying to cache from backend which returns header as Cache-Control: no-cache, no-store, max-age=0, must-revalidate
. is it possible to cache data in this scenario and want to cache for 1 minutes max? let me know your suggestion

**Comment by alombarte** [comment]
Hi @nabinkumar, if the backend does not set any caching policies this component won't work for you as it is. For a behavior like this a new feature would be required.
