### ISSUE TITLE
memcached / redis / ... distributed memory cache implementation

### ISSUE THREAD

**Issue by briveira** [krakendio/krakend-httpcache#7]
Hi there!

Krakend's doc states that the admin is responsible of the amount of RAM dedicated to the memory cache (no way to specify a maximum amount, LRU eviction, etc. 

Also, this implementation does not make use of shared cache topologies in multinode deployments (with more than one krakend running)

It's strange there is no support to Redis or memcached services.  I see you use https://github.com/gregjones/httpcache so it's a pity you can't use at least the https://github.com/gregjones/httpcache/tree/master/memcache version which would allow for a shared memcached server.

**Comment by alombarte** [comment]
Hi @briveira,

KrakenD does not rely on any external service to operate, neither shares it's state out. The cache component is consistent with this statless design, I don't understand why you say it's strange not supporting a stateful one.

If you'd like to have a distributed caching system, I would suggest adding a piece of software for this matter in front of your backend services. There is no interest on our side in increasing the complexity of this component and make it network dependent.

**Comment by briveira** [comment]
>KrakenD does not rely on any external service to operate

OK, thank you (and I get it).  And using a shared cache (not a stateful piece, but a shared memory that allows for not repeating calls to backend services, just as using a memory map as it currently uses) of course makes it network dependent.
