### ISSUE TITLE
Why depending on github.com/gregjones/httpcache

### ISSUE THREAD

**Issue by jycamier** [krakendio/krakend-httpcache#9]
HI,

i'm currently reading the documentation of KrakenD and I'm a bit surprise about this httpcache feature : 
- indeed, this is really simple...
- but it depends on github.com/gregjones/httpcache and the project is archived

Is it the same for the entreprise version ?

**Comment by kpacha** [comment]
The dependency was forked some time ago and we are using a customized, updated version (https://github.com/krakendio/httpcache).

This component is intended to be a small, in-memory and very simple cache layer ideal for caching public backend responses with low cardinality and time to live, so the httpcache package is a perfect base.

Yes, the enterprise version is also using this component

**Comment by jycamier** [comment]
Thank you @kpacha for your clear answer.
Very interresting.
